name: Repro 1

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
            cat /etc/waagent.conf
      - run: |
            set +e
            if grep -q '^AutoUpdate.UpdateToLatestVersion=' /etc/waagent.conf; then
              sudo sed -i 's/^AutoUpdate.UpdateToLatestVersion=.*/AutoUpdate.UpdateToLatestVersion=n/' /etc/waagent.conf
            else
              echo 'AutoUpdate.UpdateToLatestVersion=n' | sudo tee -a /etc/waagent.conf
            fi
      - run: |
            cat /etc/waagent.conf
